server:
  port: 8080

spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB #单个文件最大
      max-request-size: 100MB #单词请求所有文件最大
  application:
    name: purchase
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static/

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        use_sql_commonts: true

  data:
    solr:
      host: http://localhost:8983/solr/seckill/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
#  servlet:
#    multipart:
#      max-file-size: 5MB
#  profiles:
#    include: auth