server:
  port: 8080

spring:
  application:
    name: purchase
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        use_sql_commonts: true
#  servlet:
#    multipart:
#      max-file-size: 5MB
#  profiles:
#    include: auth